name: 'Setup NCA environment'
description: 'Checks out NCA, then installs the required dependencies'
runs:
  using: "composite"
  steps:
  - uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f  # v5.1.1
    with:
      python-version: 3.9
      architecture: x64
      cache: pip
  - run: pip install -r requirements.txt
    shell: bash
